version: '3.1'

services:
  db:
    image: mysql
    container_name: nest-tutorial-db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - "13306:3306"
    volumes:
      - ./src/db/initdb.d:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

volumes:
  db_data:
